"""Tests for the 20 step-result schemas + validate_step_result (KAN-57)."""

from __future__ import annotations

import copy
import json
from pathlib import Path

import jsonschema
import pytest

from vividscripts_mcp.prompts import PROMPT_INTERFACES
from vividscripts_mcp.schemas import (
    KNOWN_STEPS,
    validate_step_result,
)

_SCHEMA_DIR = Path(__file__).parents[2] / "src" / "vividscripts_mcp" / "schemas"
_FIXTURE_DIR = Path(__file__).parents[1] / "fixtures" / "step_results"

_STEP_NAMES = sorted(p.stem for p in _SCHEMA_DIR.glob("*.json"))


# ---------------------------------------------------------------------------
# Catalog alignment with KAN-56
# ---------------------------------------------------------------------------


def test_one_schema_per_prompt_interface() -> None:
    """Every PROMPT_INTERFACES entry has a schema file, and vice-versa.

    This is the cross-check that keeps KAN-56 and KAN-57 from drifting:
    add a 21st prompt and forget its schema → this test fails.
    """
    assert set(_STEP_NAMES) == set(PROMPT_INTERFACES.keys())


def test_known_steps_matches_interfaces() -> None:
    assert frozenset(PROMPT_INTERFACES.keys()) == KNOWN_STEPS


def test_output_schema_refs_resolve() -> None:
    """Every interface.output_schema_ref names a file that exists."""
    for interface in PROMPT_INTERFACES.values():
        path = _SCHEMA_DIR / interface.output_schema_ref
        assert path.is_file(), (
            f"{interface.name}: output_schema_ref {interface.output_schema_ref!r} has no file"
        )


# ---------------------------------------------------------------------------
# Schema validity
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("step", _STEP_NAMES)
def test_schema_is_valid_draft_2020_12(step: str) -> None:
    schema = json.loads((_SCHEMA_DIR / f"{step}.json").read_text(encoding="utf-8"))
    jsonschema.Draft202012Validator.check_schema(schema)


@pytest.mark.parametrize("step", _STEP_NAMES)
def test_schema_declares_object_with_required(step: str) -> None:
    schema = json.loads((_SCHEMA_DIR / f"{step}.json").read_text(encoding="utf-8"))
    assert schema["type"] == "object"
    assert schema.get("required"), f"{step}: schema has no required fields"


# ---------------------------------------------------------------------------
# Positive cases — hand-written minimal fixtures pass their own schema
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("step", _STEP_NAMES)
def test_minimal_fixture_passes(step: str) -> None:
    fixture = json.loads((_FIXTURE_DIR / f"{step}.json").read_text(encoding="utf-8"))
    ok, errors = validate_step_result(step, fixture)
    assert ok, f"{step}: minimal fixture should pass but got {errors}"


# ---------------------------------------------------------------------------
# Negative cases — generated by mutating the valid fixture
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("step", _STEP_NAMES)
def test_missing_required_field_is_rejected(step: str) -> None:
    """Dropping a required field must fail with a path-qualified error."""
    schema = json.loads((_SCHEMA_DIR / f"{step}.json").read_text(encoding="utf-8"))
    fixture = json.loads((_FIXTURE_DIR / f"{step}.json").read_text(encoding="utf-8"))
    required = schema["required"][0]
    broken = copy.deepcopy(fixture)
    del broken[required]

    ok, errors = validate_step_result(step, broken)
    assert not ok, f"{step}: dropping required {required!r} should fail"
    assert errors, f"{step}: expected error messages"


# A value that is the wrong JSON type for each declared schema type.
# (No single value is wrong for every type, so we pick per the field's
# declared type — an object-typed field needs a string to break it,
# a string-typed field needs an integer, etc.)
_WRONG_VALUE_FOR_TYPE = {
    "string": 12345,
    "integer": "not-an-integer",
    "number": "not-a-number",
    "array": "not-an-array",
    "object": "not-an-object",
    "boolean": "not-a-boolean",
}


@pytest.mark.parametrize("step", _STEP_NAMES)
def test_wrong_type_is_rejected(step: str) -> None:
    """Replacing the first required field with a wrong-typed value fails.

    The wrong value is chosen based on the field's *declared* type so the
    mutation is genuinely type-invalid (an object-typed field like
    stage_direction's ``context`` is only broken by a non-object value).
    """
    schema = json.loads((_SCHEMA_DIR / f"{step}.json").read_text(encoding="utf-8"))
    fixture = json.loads((_FIXTURE_DIR / f"{step}.json").read_text(encoding="utf-8"))
    required = schema["required"][0]
    declared_type = schema["properties"][required]["type"]
    broken = copy.deepcopy(fixture)
    broken[required] = _WRONG_VALUE_FOR_TYPE[declared_type]

    ok, _errors = validate_step_result(step, broken)
    assert not ok, (
        f"{step}: {required!r} (declared {declared_type!r}) set to a "
        f"wrong-typed value should fail validation"
    )


# ---------------------------------------------------------------------------
# validate_step_result behavior
# ---------------------------------------------------------------------------


def test_unknown_step_is_failure_not_exception() -> None:
    ok, errors = validate_step_result("not_a_real_step", {})
    assert ok is False
    assert errors == ["unknown step: 'not_a_real_step'"]


def test_error_paths_are_dotted_for_nested_failures() -> None:
    """The AC's example: paragraph_analyses[2].tension wrong type → a
    dotted path in the message."""
    bad_blueprint = {
        "genre": "horror",
        "tone": "dread",
        "narrative_structure": "three-act",
        "creative_direction": "x",
        "paragraph_analyses": [
            {"paragraph_index": 0, "tension": 5},
            {"paragraph_index": 1, "tension": 6},
            {"paragraph_index": 2, "tension": "high"},  # wrong type
        ],
    }
    ok, errors = validate_step_result("story_blueprint", bad_blueprint)
    assert not ok
    joined = " | ".join(errors)
    assert "paragraph_analyses.2.tension" in joined, f"expected dotted nested path, got: {errors}"


def test_validate_is_pure_no_mutation() -> None:
    fixture = json.loads((_FIXTURE_DIR / "narration_grouping.json").read_text(encoding="utf-8"))
    before = copy.deepcopy(fixture)
    validate_step_result("narration_grouping", fixture)
    assert fixture == before


# ---------------------------------------------------------------------------
# Schema-description drift guard (KAN-125)
# ---------------------------------------------------------------------------
#
# Three smoke-test papercuts from 2026-05-25 (Test 2) all had the same root
# cause: a schema accepted a non-string scalar / structured shape but its
# JSON-Schema had no ``description`` telling the caller what shape to
# produce. The first-pass guess was prose-shaped and validation failed in
# a way that did not tell you HOW to fix it.
#
# This guard locks down the schemas the smoke test caught (story_blueprint,
# stage_direction_bible, sound_effect_category, sound_effect_analyzer) so a
# future edit that strips a description / enum / sub-property regresses
# loudly here instead of silently in a Claude Code session.


def _load(step: str) -> dict[str, object]:
    return json.loads((_SCHEMA_DIR / f"{step}.json").read_text(encoding="utf-8"))


def test_story_blueprint_tension_description_mentions_integer_and_scale() -> None:
    """``paragraph_analyses[].tension`` is an integer 1-10; its description
    must say so explicitly. Prose like 'high' must not be a plausible guess."""
    schema = _load("story_blueprint")
    tension = schema["properties"]["paragraph_analyses"]["items"]["properties"]["tension"]  # type: ignore[index]
    desc = tension.get("description", "")  # type: ignore[attr-defined]
    assert desc, "story_blueprint.paragraph_analyses[].tension has no description"
    lowered = desc.lower()
    assert "integer" in lowered, f"tension.description must mention 'integer': {desc!r}"
    assert "1-10" in desc or "1 to 10" in lowered, (
        f"tension.description must spell out the 1-10 scale: {desc!r}"
    )
    assert tension.get("minimum") == 1 and tension.get("maximum") == 10, (  # type: ignore[attr-defined]
        "tension must declare minimum=1 and maximum=10 to match the documented scale"
    )


def test_stage_direction_bible_reference_guide_declares_object_shape() -> None:
    """``reference_guide`` is an object, not free-form prose. Its description
    must say 'object' and it must declare the expected sub-keys so the
    caller knows what to produce on the first try."""
    schema = _load("stage_direction_bible")
    rg = schema["properties"]["reference_guide"]  # type: ignore[index]
    desc = rg.get("description", "")  # type: ignore[attr-defined]
    assert desc, "stage_direction_bible.reference_guide has no description"
    assert "object" in desc.lower(), (
        f"reference_guide.description must clarify it is an object: {desc!r}"
    )
    sub_props = rg.get("properties", {})  # type: ignore[attr-defined]
    assert "characters" in sub_props and "locations" in sub_props, (
        "reference_guide must declare 'characters' and 'locations' sub-properties "
        f"(found: {sorted(sub_props)})"
    )


def test_sound_effect_category_items_describe_object_shape() -> None:
    """``selected_categories[]`` must be an object with a 'category' key,
    not a bare string. Description must convey that + an example payload."""
    schema = _load("sound_effect_category")
    sc = schema["properties"]["selected_categories"]  # type: ignore[index]
    desc = sc.get("description", "")  # type: ignore[attr-defined]
    assert desc, "sound_effect_category.selected_categories has no description"
    lowered = desc.lower()
    assert "object" in lowered, (
        f"selected_categories.description must say each item is an object: {desc!r}"
    )
    assert "category" in lowered, (
        f"selected_categories.description must name the 'category' key: {desc!r}"
    )
    assert sc.get("examples"), (  # type: ignore[attr-defined]
        "selected_categories must carry an 'examples' payload so the prompt body "
        "can show a minimal valid example"
    )


def test_sound_effect_analyzer_effects_describe_enum_and_field_names() -> None:
    """``effects[]`` had three pitfalls: time vs start, volume_level vs
    volume, enum vs 0..1 float. All three must be spelled out in the
    descriptions so the first guess succeeds."""
    schema = _load("sound_effect_analyzer")
    effects = schema["properties"]["effects"]  # type: ignore[index]
    effects_desc = effects.get("description", "")  # type: ignore[attr-defined]
    assert effects_desc, "sound_effect_analyzer.effects has no description"
    # The wrapper description should name all three exact field names so a
    # caller skimming it can't drift back to 'start' or 'volume'.
    for token in ("name", "time", "volume_level"):
        assert token in effects_desc, (
            f"effects.description must mention {token!r} so callers don't drift "
            f"to the wrong field name: {effects_desc!r}"
        )

    item_props = effects["items"]["properties"]  # type: ignore[index]

    time_desc = item_props["time"].get("description", "")
    assert time_desc and "time" in time_desc.lower(), (
        f"effects[].time needs a description referencing the field name: {time_desc!r}"
    )

    vol = item_props["volume_level"]
    vol_desc = vol.get("description", "")
    assert vol_desc, "effects[].volume_level has no description"
    assert "enum" in vol_desc.lower(), (
        f"volume_level.description must clarify it is an enum (not a float): {vol_desc!r}"
    )
    assert vol.get("enum") == ["LOW", "MEDIUM", "HIGH"], (
        f"volume_level enum must be exactly LOW/MEDIUM/HIGH, got {vol.get('enum')!r}"
    )

    assert effects.get("examples"), (  # type: ignore[attr-defined]
        "effects must carry an 'examples' payload so the prompt body can show a "
        "minimal valid example with the correct field names"
    )
